const CertificateData = [
    {
        name: 'Self-Driving Cars Specialization',
        organization: 'Coursera',
        issue_date: 'Mar 20, 2022',
        certificate_id: 'DY7MKD43EM86',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/DY7MKD43EM86',
    },
    {
        name: 'Motion Planning for Self-Driving Cars',
        organization: 'Coursera',
        issue_date: 'Mar 20, 2022',
        certificate_id: '77SZUXDF6RY6',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/77SZUXDF6RY6',
    },
    {
        name: 'Preparing for Your Review',
        organization: 'LinkedIn',
        issue_date: 'Mar 14, 2022',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/3a3a8fb3fccffabfc919e02147f3462a198ecd024bdb8d41cdeac31a19d464a4?u=2057988',
    },
    {
        name: 'Introduction to Docker: The Basics',
        organization: 'Coursera',
        issue_date: 'Feb 02, 2022',
        certificate_id: '54JQHJN2SJWS',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/54JQHJN2SJWS',
    },
    {
        name: 'Visual Perception for Self-Driving Cars',
        organization: 'Coursera',
        issue_date: 'Jan 29, 2022',
        certificate_id: 'MGAC7TV5CJNF',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/MGAC7TV5CJNF',
    },
    {
        name: 'Command Line in Linux',
        organization: 'Coursera',
        issue_date: 'Jan 07, 2022',
        certificate_id: 'ZAULKW9T4RUG',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/ZAULKW9T4RUG',
    },
    {
        name: 'Create AWS EC2 Virtual Machine Using AWS console',
        organization: 'Coursera',
        issue_date: 'Dec 30, 2021',
        certificate_id: '8CTGC4LZYN2T',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/8CTGC4LZYN2T',
    },
    {
        name: 'Budgeting and Scheduling Projects',
        organization: 'Coursera',
        issue_date: 'Dec 04, 2021',
        certificate_id: 'R7PZJKR9S2UU',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/R7PZJKR9S2UU',
    },
    {
        name: 'State Estimation and Localization for Self-Driving Cars',
        organization: 'Coursera',
        issue_date: 'Dec 04, 2021',
        certificate_id: 'FPTDLZCNGBEH',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/FPTDLZCNGBEH',
    },
    {
        name: 'Blockchain Basics',
        organization: 'Coursera',
        issue_date: 'Nov 13, 2021',
        certificate_id: '9JQYQE6CCMPP',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/9JQYQE6CCMPP',
    },
    {
        name: 'Create Your First NoSQL Database with MongoDB and Compass',
        organization: 'Coursera',
        issue_date: 'Oct 14, 2021',
        certificate_id: '3MKYLCKMTX6T',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/3MKYLCKMTX6T',
    },
    {
        name: 'Initiating and Planning Projects',
        organization: 'Coursera',
        issue_date: 'Oct 10, 2021',
        certificate_id: 'TG6BLL954R86',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/TG6BLL954R86',
    },
    {
        name: 'Introduction to Self-Driving Cars',
        organization: 'Coursera',
        issue_date: 'Oct 02, 2021',
        certificate_id: 'ZFZATNUGC2NC',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/ZFZATNUGC2NC',
    },
    {
        name: 'The Bits and Bytes of Computer Networking',
        organization: 'Coursera',
        issue_date: 'Aug 28, 2021',
        certificate_id: 'FCS52K8HHBEH',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/FCS52K8HHBEH',
    },
    {
        name: 'Deep Learning Specialization',
        organization: 'Coursera',
        issue_date: 'Jul 21, 2021',
        certificate_id: 'A4VJQLMBZ649',
        certificate_url: 'https://www.coursera.org/account/accomplishments/specialization/certificate/A4VJQLMBZ649',
    },
    {
        name: 'Sequence Models',
        organization: 'Coursera',
        issue_date: 'Jul 21, 2021',
        certificate_id: 'C8DVLRCZP2PK',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/C8DVLRCZP2PK',
    },
    {
        name: 'Getting Started with AWS Machine Learning',
        organization: 'Coursera',
        issue_date: 'Jun 19, 2021',
        certificate_id: '8G8D2NBMQB4M',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/8G8D2NBMQB4M',
    },
    {
        name: 'Convolutional Neural Networks',
        organization: 'Coursera',
        issue_date: 'Jun 10, 2021',
        certificate_id: '2EFQW6QYF94F',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/2EFQW6QYF94F',
    },
    {
        name: 'Structuring Machine Learning Projects',
        organization: 'Coursera',
        issue_date: 'May 14, 2021',
        certificate_id: '3RWKPS7DM54E',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/3RWKPS7DM54E',
    },
    {
        name: 'Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization',
        organization: 'Coursera',
        issue_date: 'May 08, 2021',
        certificate_id: 'JA3YCCQ5FQAK',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/JA3YCCQ5FQAK',
    },
    {
        name: 'Neural Networks and Deep Learning',
        organization: 'Coursera',
        issue_date: 'Apr 27, 2021',
        certificate_id: '2YBCFC4AKR26',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/2YBCFC4AKR26',
    },
    {
        name: 'The Six Morning Habits of High Performers',
        organization: 'LinkedIn',
        issue_date: 'Apr 23, 2021',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/5007446911e61a1122779f97d70b81156f27f2c96e0fe3401b988958ea3b9ee7',
    },
    {
        name: 'Machine Learning - Stanford Online',
        organization: 'Coursera',
        issue_date: 'Apr 21, 2021',
        certificate_id: '5AGLQZ9DDEBF',
        certificate_url: 'https://www.coursera.org/account/accomplishments/certificate/5AGLQZ9DDEBF',
    },
    {
        name: 'Sheryl Sandberg and Adam Grant on Option B: Building Resilience',
        organization: 'LinkedIn',
        issue_date: 'Apr 19, 2021',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/38f657f9c11d976f57157878f13e63dc73ba796af8b3bc020ba9bf4e9b8f0b98',
    },
    {
        name: '15 Secrets Successful People Know about Time Management (getAbstract Summary)',
        organization: 'LinkedIn',
        issue_date: 'Apr 19, 2021',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/bfd69262da266c4ca1dd1df2ca4af41e4f0a0f19b045bfa9b2e3a877b91cf472',
    },
    {
        name: 'Statistics Foundations: The Basics',
        organization: 'LinkedIn',
        issue_date: 'Apr 16, 2021',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/5803354fae4b15d97825ad8e3045d79a71704c210758a5208ade977ec7746c94',
    },
    {
        name: 'Embracing Unexpected Change',
        organization: 'LinkedIn',
        issue_date: 'Apr 15, 2021',
        certificate_id: '',
        certificate_url: 'https://www.linkedin.com/learning/certificates/f27396b92895e4785cdabfefe058904e742534c87af74533fcd2af94037b0ebd',
    },
    {
        name: 'Problem Solving (Intermediate)',
        organization: 'HackerRank',
        issue_date: 'Apr 11, 2021',
        certificate_id: '2b366204fb51',
        certificate_url: 'https://www.hackerrank.com/certificates/2b366204fb51',
    },
    {
        name: 'JavaScript (Basic)',
        organization: 'HackerRank',
        issue_date: 'Apr 10, 2021',
        certificate_id: 'eb427082a8e6',
        certificate_url: 'https://www.hackerrank.com/certificates/eb427082a8e6',
    },
    {
        name: 'React (Basic)',
        organization: 'HackerRank',
        issue_date: 'Sep 17, 2020',
        certificate_id: '0b9f73ef5659',
        certificate_url: 'https://www.hackerrank.com/certificates/0b9f73ef5659',
    },
    {
        name: 'C (Basic)',
        organization: 'HackerRank',
        issue_date: 'Sep 15, 2020',
        certificate_id: '41ef8c617895',
        certificate_url: 'https://www.hackerrank.com/certificates/41ef8c617895',
    },
    {
        name: 'C (Intermediate)',
        organization: 'HackerRank',
        issue_date: 'Sep 15, 2020',
        certificate_id: '98461228b33c',
        certificate_url: 'https://www.hackerrank.com/certificates/98461228b33c',
    },
    {
        name: 'Problem Solving (Basic)',
        organization: 'HackerRank',
        issue_date: 'Sep 15, 2020',
        certificate_id: '09ac66bec978',
        certificate_url: 'https://www.hackerrank.com/certificates/09ac66bec978',
    },
    {
        name: 'Python (Basic)',
        organization: 'HackerRank',
        issue_date: 'Sep 09, 2020',
        certificate_id: '8cac6fd0cd30',
        certificate_url: 'https://www.hackerrank.com/certificates/8cac6fd0cd30',
    },
    {
        name: 'Reproducible Research',
        organization: 'Coursera',
        issue_date: 'Apr 03, 2015',
        certificate_id: '',
        certificate_url: 'https://www.coursera.org/api/legacyCertificates.v1/spark/statementOfAccomplishment/973513~8253419/pdf',
    },
    {
        name: 'Image and video processing: From Mars to Hollywood with a stop at the hospital',
        organization: 'Coursera',
        issue_date: 'Mar 22, 2015',
        certificate_id: '',
        certificate_url: 'https://www.coursera.org/api/legacyCertificates.v1/spark/statementOfAccomplishment/974114~8253419/pdf',
    },
    {
        name: 'R Programming',
        organization: 'Coursera',
        issue_date: 'Oct 10, 2014',
        certificate_id: '',
        certificate_url: 'https://www.coursera.org/api/legacyCertificates.v1/spark/statementOfAccomplishment/972580~8253419/pdf',
    },
    {
        name: 'The Data Scientist’s Toolbox',
        organization: 'Coursera',
        issue_date: 'Oct 10, 2014',
        certificate_id: '',
        certificate_url: 'https://www.coursera.org/api/legacyCertificates.v1/spark/statementOfAccomplishment/972574~8253419/pdf',
    },
];

export default CertificateData;